### PR TITLE
Update example to support mcr20a

### PR DESCRIPTION
**Pull request by c1728p9**
Add the mcr20a and pull in the changes which allow runtime
configuration.

### CODE REVIEW

**Comment by MarceloSalazar** [comment]
Do we really need to add pin configs to `main.cpp`? Couldn't this be added in `mbed_app.json` ?
We may add support for many other RF drivers, so this is not great imho.

**Comment by c1728p9** [comment]
Hi @MarceloSalazar, I updated this PR to move the pins out of main.cpp. If left undefined the pins default to the appropriate Arduino pins for the shield.

**Comment by MarceloSalazar** [comment]
Is it possible to remove references to specific shields (e.g. `MCR20A_SPI_MOSI` or `ATMEL_SPI_MOSI`) from `main.cpp` and move this to a json file? (maybe this is something that could be handled by the tools?)

@sg- what's our position to scale examples to multiple targets/shields?

**Comment by sg-** [comment]
I would guess a driver should have default pins, and allow the macro to be overridden. I wonder if default pins in the constructor makes sense that way the application is simple and config can be used to override or the application can override

**Comment by c1728p9** [comment]
@sg-, is there an existing convention for default pins on shield specific drivers? I don't really have a strong preference here, so if making these the default parameters of the phys works for me. Just let me know and I'll updated it.

As for scalability, I'm don't think this is something we need to worry about at this time. Each new phy driver will only add 5-10 lines to main.cpp (less if default constructor is used), and a few files. Unused phys will get garbage collected by the linker, so they won't add size to the binary. If it is getting to the point where the example is too cluttered, we can just pick a handful of the best supported phys. @sg- what are your thoughts on the scalability of this?

**Comment by c1728p9** [comment]
Done in #21 and #22.

**Pull request closed without merging**
