### PR TITLE
Add UDP and TCP example

### PR DESCRIPTION
**Pull request by c1728p9**
PR #1 moved here

### CODE REVIEW

**Comment by maclobdell** [comment]
this is great.  otherwise the example doesn't demonstrate much

**Comment by c1728p9** [comment]
@SeppoTakalo any interest in this, or should I close it out? Sounds like there was someone in mbed-os who was wanting something like this.

**Comment by SeppoTakalo** [comment]
Hi Russ, since we don't have any other socket examples, maybe we should take these into use.

**Comment by c1728p9** [comment]
I rebased this PR on top of master and updated it builds with IAR, ARM, and GCC_ARM. Still need to run it on hardware and verify everything works. Let me know if there are any changes you want made to this PR.

**Comment by SeppoTakalo** [comment]
I have the option `platform.stdio-convert-newlines": true,` enabled in `mbed_app.json` so therefore I would prefer to use just `\n` not `\r\n`

**Comment by c1728p9** [comment]
Updated to convert "\r\n" to "\n". Also verified I could send tcp and udp commands to the device using the test scripts.

**Comment by SeppoTakalo** [comment]
Hmm.. Looks OK now.
But... It does not fit anymore into our smallest devices. (Which clearly demonstrates of how much of flash+ram is actually required to work in mesh).
I'm a bit worried on merging this in.

**Comment by c1728p9** [comment]
Which device is it too big for?

**Comment by c1728p9** [comment]
Should I add a configuration option to turn this on as an additional feature? Or maybe selectively disable it for small targets? Or I could close this PR for now and open it later if it fits.

**Comment by SeppoTakalo** [comment]
Configuration option would be nice.

Something that by default is off.

**Comment by SeppoTakalo** [comment]
This does not fit NCS36510 when using Thread router mode.
With 6LoWPAN-ND+RPL mode it fits.

**Comment by c1728p9** [comment]
Does it fit without this change using Thread router mode? I though that was never able to fit.

**Comment by SeppoTakalo** [comment]
Well, with all possible memory optimizations it seems to fit.

Looks like this example adds 2.7kB of FLASH usage. Not much for whole socket support.

**Comment by c1728p9** [comment]
Think that is enough to keep it on by default, but with an option to turn it off?

**Comment by c1728p9** [comment]
Rebased on top of master and added the option to turn off the extra features by defining MESH_MINIMAL_SMALLEST_BUILD

**Comment by BlackstoneEngineering** [comment]
Right, so as someone who is trying to make use of things, we need to either merge this or create a second example app that we surface in the Docs, cause right now I cant figure this out on my own.

**Pull request merged**
