### PR TITLE
Add official example badge

### PR DESCRIPTION
**Pull request by gpsimenos**

### CODE REVIEW

**Comment by evedon** [comment]
@mikter Any idea why CI fails as this PR does not introduce a code change?

**Comment by mikter** [comment]
ERROR] /usr/local/gcc-arm-none-eabi-9-2019-q4-major/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: out/KW41Z_GCC_ARM_internal_6lp/mbed-os/targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/fsl_common.o: in function `InstallIRQHandler':
/builds/ws/mal_PR-308-2G222WDVXU56XCMT2PRK7@3/mbed-os-example-mesh-minimal/./mbed-os/targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/fsl_common.c:61: undefined reference to `__Vectors'
collect2: error: ld returned 1 exit status

@evedon This seems to be the error, but I have no idea what is causing it @artokin any ideas

**Comment by 0xc0170** [comment]
what version of Mbed OS are you using it? The error is one we had when we updated cmsis, but was fixed in Mbed OS.

**Comment by artokin** [comment]
We had the same problem in the past: https://github.com/ARMmbed/mbed-os/issues/13062

**Comment by 0xc0170** [comment]
Correct, the fix will be in 6.1 (as I can see was merged post 6.0), unfortunately.

**Comment by evedon** [comment]
@0xc0170 I think we should go ahead wit merging this PR as there is no code change.

**Comment by 0xc0170** [comment]
@mikter  Please merge

**Pull request merged**
