### PR TITLE
Revert "Fix an incorrect multicast address."

### PR DESCRIPTION
**Pull request by MarceloSalazar**
Reverts ARMmbed/mbed-os-example-mesh-minimal#131

### CODE REVIEW

**Comment by MarceloSalazar** [comment]
cc @SeppoTakalo

**Comment by SeppoTakalo** [comment]
Please stop toggling this around.
`ff03::1` works only on Thread network.
`ff02::1` might work both, but on 6LoWPAN-ND it only works for one hop.
Reason is that 6LoWPAN setup by default does not enable the MPL routing.

This needs a proper fix that works for both, which is defining own multicast group, joining to it, and enabling MPL routing.

**Comment by MarceloSalazar** [comment]
> Please stop toggling this around.

@SeppoTakalo I don't understand your point. Here (https://github.com/ARMmbed/mbed-os-example-mesh-minimal/pull/131) you complained about merging (which you're right), so this PR was trying to give the chance to review it properly.

**Comment by SeppoTakalo** [comment]
https://github.com/ARMmbed/mbed-os-example-mesh-minimal/issues/130#issuecomment-331382353

Neither `ff03::1`or `ff02::1` would be the correct answer. Makes no sense to keep switching back and forth.

Sorry for the inconvenience, I should have referred that Kevin's comment earlier.

**Pull request closed without merging**
